version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  web:
    build: ./front
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run dev -- --host
    depends_on:
      - backend
